services:
  - type: web
    name: lupa-play
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        value: sua-chave-aqui
