services:
  - type: web
    name: lupa-play-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    repo: https://github.com/seu-usuario/lupa-play-backend